# -*- coding: utf-8 -*-
"""5340_final_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LibAdgFfg9kpj55-gh2TRdTTGWcxlWx
"""

import pandas as pd
import numpy as np

df = pd.read_table('combined_annotated_transcriptome_ids.txt')

df.head()

df1 = df.loc[:,['Transcript_ID','Chromosome','Orthogroup']]

df1.head()

df1.shape

df_galaxy = pd.read_table('/content/Galaxy73-[rLog-Normalized_counts_file_on_data_2,_data_67,_and_others].tabular')

df_galaxy.head()

df_galaxy.columns = ['Transcript_ID', 'SRR14070857:', 'SRR14070856:', 'SRR14070859:',
       'SRR14070858:']

df_galaxy['Transcript_ID'] = df_galaxy['Transcript_ID'].str.split('~~').str[-1]

df_galaxy

merged_df = pd.merge(df_galaxy,df1, on=['Transcript_ID'])

merged_df

df_M_F = pd.read_table('/content/Galaxy74-[Condition_M_vs_F].tabular', header=None)

df_M_F.columns = ['Transcript_ID','Base_mean','Log2(FC)','StdErr','Wald-Stats','P-value','P-adj']

df_M_F

df_M_F['Transcript_ID'] = df_M_F['Transcript_ID'].str.split('~~').str[-1]

merged_df_table2 = pd.merge(df_M_F,df1, on=['Transcript_ID'])

merged_df_table2.head()

merged_df_table2_final =  merged_df_table2.loc[:,['Transcript_ID','Orthogroup', 'Log2(FC)']]

merged_df_table2_final

merged_df_table2_final.to_csv(r'merged_df_table2_final.txt', header=None, index=None, sep=' ', mode='a')

df_5_greater = df_M_F.loc[(df_M_F['P-adj'] > 0.05)] # use for unbiased for table 1
df_5_greater

merged_table1_unbiased_1 = pd.merge(df_galaxy,df1,on=['Transcript_ID']) ####First Merge
merged_table1_unbiased_2 =pd.merge(merged_table1_unbiased_1,df_5_greater,on=['Transcript_ID'])

#### Second Merge #### First and second merge produce the same output
df_unbiased = pd.merge(pd.merge(df_galaxy,df1,on='Transcript_ID'),df_5_greater,on='Transcript_ID')

df_unbiased.loc[(df_unbiased['Chromosome']== 'LG10')]



df_5_less = df_M_F.loc[(df_M_F['P-adj'] < 0.05)]
df_5_less # use for log2FC for table 1 (X-10)

merged_table1_new = pd.merge(df_5_less,df1,on=['Transcript_ID'])
merged_table1_new

merged_table1 = pd.merge(pd.merge(df1,df_5_less,on='Transcript_ID'),df_galaxy,on='Transcript_ID')
merged_table1

f_chX = merged_table1.loc[((merged_table1['Chromosome']== 'LGX') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_chX.shape

m_chX = merged_table1.loc[((merged_table1['Chromosome']== 'LGX') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_chX.shape

f_ch2 = merged_table1.loc[((merged_table1['Chromosome']== 'LG2') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch2.shape

m_ch2 = merged_table1.loc[((merged_table1['Chromosome']== 'LG2') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch2.shape

f_ch3 = merged_table1.loc[((merged_table1['Chromosome']== 'LG3') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch3.shape

m_ch3 = merged_table1.loc[((merged_table1['Chromosome']== 'LG3') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch3.shape

f_ch4 = merged_table1.loc[((merged_table1['Chromosome']== 'LG4') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch4.shape

m_ch4 = merged_table1.loc[((merged_table1['Chromosome']== 'LG4') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch4.shape

f_ch5 = merged_table1.loc[((merged_table1['Chromosome']== 'LG5') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch5.shape

m_ch5 = merged_table1.loc[((merged_table1['Chromosome']== 'LG5') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch5.shape

f_ch6 = merged_table1.loc[((merged_table1['Chromosome']== 'LG6') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch6.shape

m_ch6 = merged_table1.loc[((merged_table1['Chromosome']== 'LG6') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch6.shape

f_ch7 = merged_table1.loc[((merged_table1['Chromosome']== 'LG7') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch7.shape

m_ch7 = merged_table1.loc[((merged_table1['Chromosome']== 'LG7') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch7.shape

f_ch8 = merged_table1.loc[((merged_table1['Chromosome']== 'LG8') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch8.shape

m_ch8 = merged_table1.loc[((merged_table1['Chromosome']== 'LG8') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch8.shape

f_ch9 = merged_table1.loc[((merged_table1['Chromosome']== 'LG9') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch9.shape

m_ch9 = merged_table1.loc[((merged_table1['Chromosome']== 'LG9') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch9.shape

f_ch10 = merged_table1.loc[((merged_table1['Chromosome']== 'LG10') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
f_ch10.shape

m_ch10 = merged_table1.loc[((merged_table1['Chromosome']== 'LG10') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
m_ch10.shape

un = merged_table1.loc[((merged_table1['Chromosome']== 'un') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <0 ))]
un.shape

un_ch = merged_table1.loc[((merged_table1['Chromosome']== 'un') & (merged_table1['P-adj'] < 0.05) & (merged_table1['Log2(FC)'] <2) & (merged_table1['Log2(FC)'] >0 ))]
un_ch.shape

merged_table1.loc[(merged_table1['Log2(FC)'] >2 )]

merged_table1.loc[(merged_table1['Chromosome']== 'un')]